// const Icons = {
//     email: require('./icons/email.png'),
//     pass: require('./icons/Icon.png'),
//     eye: require('./icons/lock-01.png'),
//   };
  const Images = {
    landing_page: require('./images/LandingPage.png'),
    white: require('./images/White.png'),
    imgBack: require('./images/1.png'),
    white2: require('./images/White2.png'),
    quivioYourPersonal: require('./images/QUIVIOYourPersonalCarWashAssistant.png'),
    L1: require('./images/L1.png'),
    L2: require('./images/L2.png'),
    email: require('./images/email.png'),
    eye: require('./images/Icon.png'),
    pass: require('./images/lock-01.png'),
    alert_circle:  require('./images/alert-circle.png'),
    hide: require('./images/hide.png'),
    lock: require('./images/lockModal.png'),
    mask_group: require('./images/Maskgroup.png'),
    back_arrow: require('./images/backArrow.png'),
    modalicon2: require('./images/modalicon2.png'),
    vector_reset: require('./images/VectorReset.png'),
    modal_reset: require('./images/ModalReset.png'),
    img_modal: require('./images/imgModal.png'),
    m1: require('./images/M1.png'),
    m2: require('./images/M2.png'),
    m3:  require('./images/M3.png'),
    exit2FA:  require('./images/exit2FA.png'),
    chat:  require('./images/chat.png'),
    bell:  require('./images/bell.png'),
    setupImg:  require('./images/fi_807262.png'),
    f1:  require('./images/f1.png'),
    f2:  require('./images/f2.png'),
    flatlistIcon:  require('./images/flatlistIcon.png'),
  };
  
  export default Images;